openapi: 3.0.0
info:
  title: Checkout API
  description: Checkout API for e-commerce platform
  version: 1.0.0

servers:
  - url: /
    description: API server

tags:
  - name: Checkout
    description: Checkout operations
  - name: Payment
    description: Payment processing operations

paths:
  /api/v1/checkouts:
    get:
      tags:
        - Checkout
      summary: List checkouts
      description: Retrieves a paginated list of checkouts
      parameters:
        - name: page
          in: query
          description: Page number
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckoutListResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      tags:
        - Checkout
      summary: Create a new checkout
      description: Process cart and create a checkout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cart_id:
                  type: string
                  format: uuid
                  description: ID of the cart to checkout
              required:
                - cart_id
      responses:
        "201":
          description: Checkout created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckoutResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Cart not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Cart already checked out
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/checkouts/{id}:
    get:
      tags:
        - Checkout
      summary: Get checkout by ID
      description: Retrieves a checkout by its ID
      parameters:
        - name: id
          in: path
          required: true
          description: Checkout ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckoutResponse"
        "404":
          description: Checkout not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    StandardResponse:
      type: object
      required:
        - data
        - message
        - code
        - server_time
      properties:
        data:
          type: object
          description: Response data payload
        message:
          type: string
          description: Response message
        code:
          type: string
          description: Response code
        server_time:
          type: string
          format: date-time
          description: Server timestamp

    ErrorResponse:
      type: object
      required:
        - message
        - code
        - server_time
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        data:
          type: object
          description: Additional error data
          nullable: true
        server_time:
          type: string
          format: date-time
          description: Server timestamp

    CheckoutListResponse:
      allOf:
        - $ref: "#/components/schemas/StandardResponse"
        - type: object
          properties:
            data:
              type: object
              properties:
                checkouts:
                  type: array
                  items:
                    $ref: "#/components/schemas/CheckoutSummary"
                meta:
                  $ref: "#/components/schemas/PaginationMeta"

    CheckoutResponse:
      allOf:
        - $ref: "#/components/schemas/StandardResponse"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/Checkout"

    PaginationMeta:
      type: object
      properties:
        current_page:
          type: integer
        per_page:
          type: integer
        total:
          type: integer
        total_pages:
          type: integer
    CheckoutSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        cart_id:
          type: string
          format: uuid
        subtotal:
          type: number
          format: float
        total_discount:
          type: number
          format: float
        total:
          type: number
          format: float
        created_at:
          type: string
          format: date-time
    Checkout:
      type: object
      properties:
        id:
          type: string
          format: uuid
        cart_id:
          type: string
          format: uuid
        items:
          type: array
          items:
            $ref: "#/components/schemas/CheckoutItem"
        promotions:
          type: array
          items:
            $ref: "#/components/schemas/PromotionApplied"
        subtotal:
          type: number
          format: float
        total_discount:
          type: number
          format: float
        total:
          type: number
          format: float
        created_at:
          type: string
          format: date-time
    CheckoutItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        checkout_id:
          type: string
          format: uuid
        product_id:
          type: string
          format: uuid
        product_sku:
          type: string
        product_name:
          type: string
        quantity:
          type: integer
        unit_price:
          type: number
          format: float
        subtotal:
          type: number
          format: float
        discount:
          type: number
          format: float
        total:
          type: number
          format: float
    PromotionApplied:
      type: object
      properties:
        id:
          type: string
          format: uuid
        checkout_id:
          type: string
          format: uuid
        promotion_id:
          type: string
          format: uuid
        description:
          type: string
        discount:
          type: number
          format: float
