name: Pull Request

on:
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod download

      - name: Install oapi-codegen v2
        run: go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

      - name: Generate HTTP code
        run: |
          echo "Generating HTTP code from OpenAPI specs"
          make gen-http || ./scripts/generate.sh

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod download

      - name: Install oapi-codegen v2
        run: go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

      - name: Generate HTTP code
        run: |
          echo "Generating HTTP code from OpenAPI specs"
          make gen-http || ./scripts/generate.sh

      - name: Build
        run: go build -v ./cmd/core

  generate:
    name: Generate
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod download

      - name: Install oapi-codegen v2
        run: go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

      - name: Generate HTTP code
        run: |
          echo "Generating HTTP code from OpenAPI specs"
          make gen-http || ./scripts/generate.sh

      - name: Generate code
        run: go generate ./...
