name: CD - Push to Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Install oapi-codegen v2
        run: go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

      - name: Generate HTTP code
        run: |
          echo "Generating HTTP code from OpenAPI specs"
          make gen-http || ./scripts/generate.sh

      - name: Build Go application
        run: go build -v ./cmd/core

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/e-commerce-be:latest,${{ secrets.DOCKER_HUB_USERNAME }}/e-commerce-be:${{ github.sha }}
          build-args: |
            DB_HOST=host.docker.internal
            APP_ENV=production
            SWAGGER_HOST=${SWAGGER_HOST:-host.docker.internal}

      - name: Echo success message
        run: echo "Successfully built and pushed Docker image to Docker Hub as ${{ secrets.DOCKER_HUB_USERNAME }}/e-commerce-be:latest"
